name: Structure Hash Writer

on:
  push:
    paths-ignore:
      - 'hash_manifest.json'
  pull_request:
    paths-ignore:
      - 'hash_manifest.json'
  workflow_dispatch:

jobs:
  embed-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set upload author and timestamp
        run: |
          echo "UPLOADER=Fyorigin" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV

      - name: Embed hashes and update manifest
        run: |
          echo "{" > hash_manifest.json
          first=1

          find . -type f \
            ! -path "./.git/*" \
            ! -path "./.github/*" \
            ! -name "hash_manifest.json" | while read file; do

            ext="${file##*.}"
            hash=$(sha256sum "$file" | awk '{print $1}')
            embed=false

            case "$ext" in
              md|txt|yml|yaml|html|xml)
                # Insert hash if not already embedded
                if ! grep -q "$hash" "$file"; then
                  comment=""
                  case "$ext" in
                    md|html) comment="<!-- STRUCTURE-ID: sha256:$hash uploaded_by: $UPLOADER at $TIMESTAMP -->" ;;
                    yml|yaml|txt) comment="# STRUCTURE-ID: sha256:$hash uploaded_by: $UPLOADER at $TIMESTAMP" ;;
                    xml) comment="<!-- STRUCTURE-ID: sha256:$hash uploaded_by: $UPLOADER at $TIMESTAMP -->" ;;
                  esac
                  echo "$comment" >> "$file"
                fi
                embed=true
                ;;
              *)
                embed=false
                ;;
            esac

            if [ $first -eq 0 ]; then echo "," >> hash_manifest.json; fi
            echo "  \"${file}\": {\"sha256\": \"${hash}\", \"timestamp\": \"${TIMESTAMP}\", \"embedded\": ${embed}, \"uploader\": \"${UPLOADER}\"}" >> hash_manifest.json
            first=0
          done

          echo "" >> hash_manifest.json
          echo "}" >> hash_manifest.json

      - name: Commit and push hash updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "structure-bot"
          git config user.email "structure-bot@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-embed structure hashes and update manifest"
            git push
          fi
