name: Structure Hash Writer

on:
  push:
    paths-ignore:
      - 'hash_manifest*.json'
      - 'hash_diff_report*.md'
  workflow_dispatch:

jobs:
  embed-hash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set author and timestamp
        run: |
          echo "UPLOADER=Fyorigin" >> $GITHUB_ENV
          echo "TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
          echo "DATE=$(date -u +"%Y-%m-%d")" >> $GITHUB_ENV

      - name: Prepare hash logs
        run: |
          mkdir -p hash_log
          if [ -f hash_log/hash_manifest_latest.json ]; then
            cp hash_log/hash_manifest_latest.json hash_log/hash_manifest_prev.json
          else
            echo "{}" > hash_log/hash_manifest_prev.json
          fi
          cp hash_log/hash_manifest_prev.json hash_log/hash_manifest_new.json

      - name: Scan and update hashes
        run: |
          report="hash_log/hash_diff_report_${DATE}.md"
          manifest_new="hash_log/hash_manifest_new.json"

          echo "# Hash Diff Report - $TIMESTAMP" > "$report"
          echo "" >> "$report"
          echo "| File | Status | Old Hash | New Hash |" >> "$report"
          echo "|------|--------|----------|----------|" >> "$report"

          find . -type f \
            ! -path "./.git/*" \
            ! -path "./.github/*" \
            ! -path "./hash_log/*" \
            ! -name "*.json" \
            ! -name "*.md" -o -name "*.md" \
            | while read file; do
              hash=$(sha256sum "$file" | awk '{print $1}')
              old_hash=$(jq -r --arg f "$file" '.[$f].sha256 // empty' hash_log/hash_manifest_prev.json)
              if [ "$hash" != "$old_hash" ]; then
                echo "Updating: $file"
                jq --arg f "$file" --arg h "$hash" --arg t "$TIMESTAMP" \
                  '. + {($f): {"sha256": $h, "timestamp": $t}}' \
                  "$manifest_new" > tmp && mv tmp "$manifest_new"

                echo "| $file | Modified | $old_hash | $hash |" >> "$report"

                if [[ "$file" == *.md ]]; then
                  echo "" >> "$file"
                  echo "<!-- STRUCTURE-ID: sha256:$hash uploaded_by: $UPLOADER at $TIMESTAMP -->" >> "$file"
                fi
              fi
            done

      - name: Finalize manifest and commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cp hash_log/hash_manifest_new.json hash_log/hash_manifest_latest.json
          cp hash_log/hash_manifest_new.json "hash_log/hash_manifest_${DATE}.json"

          git config user.name "structure-bot"
          git config user.email "structure-bot@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Hash update on $DATE with structure tag embedding"
            git pull origin main --rebase
            git push origin main
          fi
