name: Validate Embedded Hashes

on:
  workflow_dispatch:

jobs:
  validate-hashes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Validate embedded hashes
        run: |
          echo "{" > hash_validation_report.json
          echo "| File | Embedded | Actual | Match |" > hash_validation_report.md
          echo "|------|----------|--------|-------|" >> hash_validation_report.md
          first=1
          for file in $(find . -type f             ! -path "./.git/*"             ! -path "./.github/*"             ! -name "hash_manifest.json"             ! -name "hash_validation_report.json"             ! -name "hash_validation_report.md"); do
              embedded_hash=$(grep -Eo 'Commit hash: [a-f0-9]+' "$file" | awk '{print $3}')
              if [ ! -z "$embedded_hash" ]; then
                actual_hash=$(sha256sum "$file" | awk '{print $1}')
                manifest_hash=$(jq -r --arg f "$file" '.[$f].sha256' hash_manifest.json)
                match=false
                if [[ "$manifest_hash" == "$actual_hash" ]]; then
                  match=true
                fi
                if [ $first -eq 0 ]; then echo "," >> hash_validation_report.json; fi
                echo "  "${file}": {"embedded": "${embedded_hash}", "actual": "${manifest_hash}", "match": ${match}}" >> hash_validation_report.json
                echo "| ${file} | \`${embedded_hash}\` | \`${manifest_hash}\` | ${match} |" >> hash_validation_report.md
                first=0
              fi
          done
          echo "" >> hash_validation_report.json
          echo "}" >> hash_validation_report.json

      - name: Commit and push hash validation report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hash_validation_report.json hash_validation_report.md
          if git diff --cached --quiet; then
            echo "No changes in validation reports"
          else
            git commit -m "Update hash validation reports (json + markdown)"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
