name: Reverse Hash Self-Reference Check

on:
  workflow_dispatch:

jobs:
  reverse-hash-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Check for self-declared hashes
        run: |
          echo "{" > hash_validation_report.json
          echo "| File | Real Hash | Declared In File | Matches Manifest |" > hash_validation_report.md
          echo "|------|-----------|------------------|-------------------|" >> hash_validation_report.md
          first=1
          for file in $(find . -type f             ! -path "./.git/*"             ! -path "./.github/*"             ! -name "hash_manifest.json"             ! -name "hash_validation_report.json"             ! -name "hash_validation_report.md"); do

              real_hash=$(sha256sum "$file" | awk '{print $1}')
              short_hash=$(echo "$real_hash" | cut -c1-7)
              found_hash=false
              if grep -q "$real_hash" "$file" || grep -q "$short_hash" "$file"; then
                found_hash=true
              fi

              manifest_hash=$(jq -r --arg f "$file" '.[$f].sha256' hash_manifest.json)
              manifest_match=false
              if [[ "$manifest_hash" == "$real_hash" ]]; then
                manifest_match=true
              fi

              if [ $first -eq 0 ]; then echo "," >> hash_validation_report.json; fi
              echo "  "${file}": {"sha256": "${real_hash}", "declared_in_file": ${found_hash}, "in_manifest": ${manifest_match}}" >> hash_validation_report.json
              echo "| ${file} | \`${real_hash}\` | ${found_hash} | ${manifest_match} |" >> hash_validation_report.md
              first=0
          done
          echo "" >> hash_validation_report.json
          echo "}" >> hash_validation_report.json

      - name: Commit and push reverse hash report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add hash_validation_report.json hash_validation_report.md
          if git diff --cached --quiet; then
            echo "No changes in hash validation report"
          else
            git commit -m "Update hash validation report"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          fi
